version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    env_file:
      - .env  # Load from .env file
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: employee_reports
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: employee_app
    depends_on:
      - db
    env_file:
      - .env  # Load from .env file
    environment:
      RUNNING_IN_DOCKER: "true"  # Important for auto-detection
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: employee_reports
      DB_PORT: 5432
    ports:
      - "8000:8000"

volumes:
  postgres_data: