database:
  user: myuser
  password: mypassword
  host: localhost
  port: 5432
  name: employee_reports
  url: postgresql://myuser:mypassword@localhost:5432/employee_reports

llm:
  provider: ollama  # Options: ollama, openai (future)
  api_url: http://localhost:11434/api/generate
  model: llama3.1:8b

app:
  debug: true

vector_db:
  host: localhost  # Change to 'qdrant' if running in Docker
  port: 6333
  storage_path: ./qdrant_data  # Change to '/qdrant/storage' in Docker
  collection_name: employee_reports  # Collection name for storing vectors
